# ------------------------------------------------------------------------------
# https://help.github.com/articles/configuring-jekyll/

## github default ##
github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate

## github overwrite ##
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
    noscript: false

# ------------------------------------------------------------------------------
## customization ##

# https://github.com/swanson/lagom
# more configure options @ _data/theme.yml
title: Happy Blooming
name: Dyno Fu
#email: dyno.fu@gmail.com
email: "'ZHluby5mdUBnbWFpbC5jb20='.decode('base64')"
#url: http://dyno.github.io
url: http://blog.dynofu.me
description:
    Reality, with all its ambiguities, does the job just fine. - GEORGE DYSON

exclude: [zold, LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

paginate: 20

